### ISSUE TITLE
NVRChannel not working over unencrypted connections

### ISSUE THREAD

**Issue by EternityForest** [EternityForest/KaithemAutomation#2]
ERROR:2022Apr07 17:15:07 BST cherrypy.error.3020579360 [07/Apr/2022:17:15:07] HTTP    Traceback (most recent call last):
File "/opt/kaithem/kaithem/src/thirdparty/cherrypy/_cprequest.py", line 638, in respond     self._do_respond(path_info)
File "/opt/kaithem/kaithem/src/thirdparty/cherrypy/_cprequest.py", line 688, in   _do_respond
self.hooks.run('before_request_body')   File "/opt/kaithem/kaithem/src/thirdparty/cherrypy/_cprequest.py", line 95, in
run     self.run_hooks(iter(sorted(self[point])))   File   "/opt/kaithem/kaithem/src/thirdparty/cherrypy/_cprequest.py",
line 117, in run_hooks     hook()   File "/opt/kaithem/kaithem/src/thirdparty/cherrypy/_cprequest.py", line 65, in
__call__     return self.callback(**self.kwargs)   File
"/opt/kaithem/kaithem/src/thirdparty/ws4py/server/cherrypyserver.py", line 191, in upgrade     request.ws_handler =
handler_cls(ws_conn, ws_protocols, ws_extensions,   File "/opt/kaithem/kaithem/src/widgets.py", line 445, in __init__
if cherrypy.request.scheme == 'https' or pages.

For now the workaround is just to use https(Default port 8001) and click through the security stuff.  Proper HTTP support coming soon.

**Comment by EternityForest** [comment]
Fixed in latest release.
